'use strict';

// id:          为与服务器约定的序号，外部不能更改
// tableName:   表名
// data / dataMap:        配合 读取表逻辑提供缓存回调函数 使用
// dataVersion: 缓存的数据版本号
// version:     为服务器的版本号，从接口获得，不用再代码里面填写，由逻辑操控

const HClientTables = {
    CS_GiftList: { id: 0, tableName: 'CS_GiftList' },
    CS_CarList: { id: 1, tableName: 'CS_CarList' },
    CS_CuteNumberManager: { id: 2, tableName: 'CS_CuteNumberManager' },
    CS_LiveSetUp: { id: 3, tableName: 'CS_LiveSetUp' },
    MusicList: { id: 4, tableName: 'MusicList' },
    SystemConfig: { id: 5, tableName: 'SystemConfig' },
    ResultStatus: { id: 6, tableName: 'ResultStatus' },
    Language: { id: 7, tableName: 'Language' },
    Message: { id: 8, tableName: 'Message' },
    Recharge: { id: 9, tableName: 'Recharge' },
    RandomName: { id: 10, tableName: 'RandomName' },
    Task: { id: 11, tableName: 'Task' },
    PublicConfig: { id: 12, tableName: 'PublicConfig' },
    Level: { id: 13, tableName: 'Level' },
    CharmLevel: { id: 14, tableName: 'CharmLevel' },
    ContributeLevel: { id: 15, tableName: 'ContributeLevel' },
    Position: { id: 16, tableName: 'Position' },
    Slogan: { id: 17, tableName: 'Slogan' },
    RandomRobotName: { id: 18, tableName: 'RandomRobotName' },
    ActivityInfo: { id: 19, tableName: 'ActivityInfo' },
    FunRoomDividedRateMode: { id: 20, tableName: 'FunRoomDividedRateMode' },
    HeadFrame: { id: 21, tableName: 'HeadFrame' },
    SureLiveKeywords: { id: 22, tableName: 'SureLiveKeywords' },
    CS_GiftLabel: { id: 23, tableName: 'CS_GiftLabel' },
    CS_PackageTag: { id: 24, tableName: 'CS_PackageTag' },
    CS_StartAdvertList: { id: 25, tableName: 'CS_StartAdvertList' },
    CS_VoiceFriendBanner: { id: 26, tableName: 'CS_VoiceFriendBanner' },
    CS_VoiceRoomBackground: { id: 27, tableName: 'CS_VoiceRoomBackground' },
    ChatFilterWordKey: { id: 28, tableName: 'ChatFilterWordKey' },
    GiftConfig: { id: 29, tableName: 'GiftConfig' },
    FAQ: { id: 30, tableName: 'FAQ' },
    RandomMatchingTips: { id: 31, tableName: 'RandomMatchingTips' },
    RoomType: { id: 32, tableName: 'RoomType' },
    RecreationConfig: { id: 33, tableName: 'RecreationConfig' },
    RandomRoomName: { id: 34, tableName: 'RandomRoomName' },
    Sign: { id: 35, tableName: 'Sign' },
    NewHandPkg: { id: 36, tableName: 'NewHandPkg' },
    YinXiao: { id: 37, tableName: 'YinXiao' },
    TrueWord: { id: 38, tableName: 'TrueWord' },
    CS_AvatarBox: { id: 39, tableName: 'CS_AvatarBox' },
    CS_DialogBox: { id: 40, tableName: 'CS_DialogBox' },
    CS_Topic: { id: 41, tableName: 'CS_Topic' },
    ResourceVersion: { id: 42, tableName: 'ResourceVersion' },
    RandomGoodHead: { id: 43, tableName: 'RandomGoodHead' },
    CS_ChannelInfo: { id: 44, tableName: 'CS_ChannelInfo' },
    Behavior: { id: 45, tableName: 'Behavior' },
    PatrolManager: { id: 46, tableName: 'PatrolManager' },
    CS_OfficialList: { id: 47, tableName: 'CS_OfficialList' },
    CS_CuteNumber: { id: 48, tableName: 'CS_CuteNumber' },
    CS_RoomLabelManager: { id: 49, tableName: 'CS_RoomLabelManager' },
    CS_RoomLabel: { id: 50, tableName: 'CS_RoomLabel' },
    CS_SureLiveKeywords: { id: 51, tableName: 'CS_SureLiveKeywords' },
    TuneQualityConfig: { id: 52, tableName: 'TuneQualityConfig' },
    AvatarBoxConfig: { id: 53, tableName: 'AvatarBoxConfig' },
    FriendRoomWriteList: { id: 54, tableName: 'FriendRoomWriteList' },
    CS_PrizeRule: { id: 55, tableName: 'CS_PrizeRule' },
    CS_RoomFriendBanner: { id: 56, tableName: 'CS_RoomFriendBanner' },
    CS_WriteList: { id: 57, tableName: 'CS_WriteList' },
    CS_AntiSpamConfig: { id: 58, tableName: 'CS_AntiSpamConfig' },
    MatchSensitiveRegexp: { id: 59, tableName: 'MatchSensitiveRegexp' },
    VisitorModelConfig: { id: 60, tableName: 'VisitorModelConfig' },
    CS_ContentControlConfig: { id: 61, tableName: 'CS_ContentControlConfig' },
    RandomMatchingThesaurus: { id: 62, tableName: 'RandomMatchingThesaurus' },
    GuardianLevel: { id: 63, tableName: 'GuardianLevel' },
    GuardianTask: { id: 64, tableName: 'GuardianTask' },
    CS_RoomFriendSmallBanner: { id: 65, tableName: 'CS_RoomFriendSmallBanner' },
    CPRoomWhiteList: { id: 66, tableName: 'CPRoomWhiteList' },
    CS_RedEnvelopeRule: { id: 67, tableName: 'CS_RedEnvelopeRule' },
    CS_TestSubject: { id: 68, tableName: 'CS_TestSubject' },
    CS_TreasureBox: { id: 69, tableName: 'CS_TreasureBox' },
    CS_Medal: { id: 70, tableName: 'CS_Medal' },
    MomentConfig: { id: 71, tableName: 'MomentConfig' },
    EggDisplayConfig: { id: 72, tableName: 'EggDisplayConfig' },
    TreasureBoxDisplayConfig: { id: 73, tableName: 'TreasureBoxDisplayConfig' },
    GrabHatConfig: { id: 74, tableName: 'GrabHatConfig' },
    BERoomWhiteList: { id: 75, tableName: 'BERoomWhiteList' },
    VideoWhitelist: { id: 76, tableName: 'VideoWhitelist' },
    Majiabao: { id: 77, tableName: 'Majiabao' },
    CS_SquareBanner: { id: 78, tableName: 'CS_SquareBanner' },
    GiftTipConfig: { id: 79, tableName: 'GiftTipConfig' },
    VideoRoomWhiteList: { id: 80, tableName: 'VideoRoomWhiteList' },
    CS_MatchmakerConfig: { id: 81, tableName: 'CS_MatchmakerConfig' },
    VideoRoomSalaryConfig: { id: 82, tableName: 'VideoRoomSalaryConfig' },
    CS_CommonBanner: { id: 83, tableName: 'CS_CommonBanner' },
    LiveReview: { id: 84, tableName: 'LiveReview' },
    RoomListChannelFilter: { id: 85, tableName: 'RoomListChannelFilter' },
    CS_FishConfig: { id: 86, tableName: 'CS_FishConfig' },
    RankFilterList: { id: 87, tableName: 'RankFilterList' },
    GrabHatRoomFilter: { id: 88, tableName: 'GrabHatRoomFilter' },
    CrossRoomConfig: { id: 89, tableName: 'CrossRoomConfig' },
    PKLevel: { id: 90, tableName: 'PKLevel' },
    CS_AppBottomTab: { id: 91, tableName: 'CS_AppBottomTab' },
    SmashEggMessage: { id: 92, tableName: 'SmashEggMessage' },
    FunRobotManual: { id: 93, tableName: 'FunRobotManual' },
    MoneyGivingList: { id: 94, tableName: 'MoneyGivingList' },
    RobotCopywriter: { id: 95, tableName: 'RobotCopywriter' },
    WebConfig: { id: 96, tableName: 'WebConfig' },
    AnchorChattingServiceEarningsRatio: { id: 97, tableName: 'AnchorChattingServiceEarningsRatio' },
    ChatterLabel: { id: 98, tableName: 'ChatterLabel' },
    VipAuthentication: { id: 99, tableName: 'VipAuthentication' },
    CS_SmashEggActivityRule: { id: 100, tableName: 'CS_SmashEggActivityRule' },


}

export default HClientTables;