'use strict';

import {ActivityCmd, AdviseCmd, AlbumCmd, BagCmd, CardCmd, CenterCmd, CommentCmd, DataCmd, FishCmd, GiftPackageCmd, GmCmd, GroupCmd, GuardianCmd, HeartBeatCmd, LiveRoomCmd, MessageCmd, MomentCmd, MyCmd, NewLiveRoomCmd, NotificationCmd, PublicChatCmd, RechargeCmd, RedEnvelopeCmd, RoomCmd, ServiceCmd, ShortcutMessageCmd, SkillChatCmd, SkillCmd, SmashEggCmd, TestCmd, UserCertificationCmd, UserCmd} from '../protobuf/request';
import SocketModel from './network/SocketModel';
import ApiModel from './network/ApiModel';

const requestSocket = SocketModel.request;
const requestCenter = ApiModel.requestCenter;

export const ActivityCmd_activityPop = (params, timeout) => { return requestSocket(ActivityCmd.activityPop.encode, 1005, params, true, timeout, 'ActivityCmd.activityPop'); }
export const ActivityCmd_clientTriggerTask = (params, timeout) => { return requestSocket(ActivityCmd.clientTriggerTask.encode, 1003, params, true, timeout, 'ActivityCmd.clientTriggerTask'); }
export const ActivityCmd_drawNewHandPkg = (params, timeout) => { return requestSocket(ActivityCmd.drawNewHandPkg.encode, 1008, params, true, timeout, 'ActivityCmd.drawNewHandPkg'); }
export const ActivityCmd_drawTaskAward = (params, timeout) => { return requestSocket(ActivityCmd.drawTaskAward.encode, 1002, params, true, timeout, 'ActivityCmd.drawTaskAward'); }
export const ActivityCmd_getActivityState = (params, timeout) => { return requestSocket(ActivityCmd.getActivityState.encode, 1004, params, true, timeout, 'ActivityCmd.getActivityState'); }
export const ActivityCmd_getNewHandPkgData = (params, timeout) => { return requestSocket(ActivityCmd.getNewHandPkgData.encode, 1179, params, true, timeout, 'ActivityCmd.getNewHandPkgData'); }
export const ActivityCmd_getSignData = (params, timeout) => { return requestSocket(ActivityCmd.getSignData.encode, 1007, params, true, timeout, 'ActivityCmd.getSignData'); }
export const ActivityCmd_getTaskList = (params, timeout) => { return requestSocket(ActivityCmd.getTaskList.encode, 1001, params, true, timeout, 'ActivityCmd.getTaskList'); }
export const ActivityCmd_sign = (params, timeout) => { return requestSocket(ActivityCmd.sign.encode, 1006, params, true, timeout, 'ActivityCmd.sign'); }
export const AdviseCmd_advise = (params, timeout) => { return requestSocket(AdviseCmd.advise.encode, 1241, params, true, timeout, 'AdviseCmd.advise'); }
export const AdviseCmd_adviseList = (params, timeout) => { return requestSocket(AdviseCmd.adviseList.encode, 1242, params, true, timeout, 'AdviseCmd.adviseList'); }
export const AdviseCmd_adviseReplyList = (params, timeout) => { return requestSocket(AdviseCmd.adviseReplyList.encode, 1243, params, true, timeout, 'AdviseCmd.adviseReplyList'); }
export const AdviseCmd_readAdviseReply = (params, timeout) => { return requestSocket(AdviseCmd.readAdviseReply.encode, 1244, params, true, timeout, 'AdviseCmd.readAdviseReply'); }
export const AlbumCmd_addPhotos = (params, timeout) => { return requestSocket(AlbumCmd.addPhotos.encode, 1009, params, true, timeout, 'AlbumCmd.addPhotos'); }
export const AlbumCmd_delAlbum = (params, timeout) => { return requestSocket(AlbumCmd.delAlbum.encode, 1011, params, true, timeout, 'AlbumCmd.delAlbum'); }
export const AlbumCmd_delPhotos = (params, timeout) => { return requestSocket(AlbumCmd.delPhotos.encode, 1010, params, true, timeout, 'AlbumCmd.delPhotos'); }
export const AlbumCmd_getAlbums = (params, timeout) => { return requestSocket(AlbumCmd.getAlbums.encode, 1012, params, true, timeout, 'AlbumCmd.getAlbums'); }
export const BagCmd_buyCar = (params, timeout) => { return requestSocket(BagCmd.buyCar.encode, 1015, params, true, timeout, 'BagCmd.buyCar'); }
export const BagCmd_buyGoods = (params, timeout) => { return requestSocket(BagCmd.buyGoods.encode, 1197, params, true, timeout, 'BagCmd.buyGoods'); }
export const BagCmd_buyHeadFrame = (params, timeout) => { return requestSocket(BagCmd.buyHeadFrame.encode, 1189, params, true, timeout, 'BagCmd.buyHeadFrame'); }
export const BagCmd_getGoodsList = (params, timeout) => { return requestSocket(BagCmd.getGoodsList.encode, 1014, params, true, timeout, 'BagCmd.getGoodsList'); }
export const BagCmd_getReceiveGiftLog = (params, timeout) => { return requestSocket(BagCmd.getReceiveGiftLog.encode, 1025, params, true, timeout, 'BagCmd.getReceiveGiftLog'); }
export const BagCmd_getReceiveGifts = (params, timeout) => { return requestSocket(BagCmd.getReceiveGifts.encode, 1024, params, true, timeout, 'BagCmd.getReceiveGifts'); }
export const BagCmd_getSendGifts = (params, timeout) => { return requestSocket(BagCmd.getSendGifts.encode, 1907, params, true, timeout, 'BagCmd.getSendGifts'); }
export const BagCmd_getWallet = (params, timeout) => { return requestSocket(BagCmd.getWallet.encode, 1013, params, true, timeout, 'BagCmd.getWallet'); }
export const BagCmd_sendAllMyPkgGifts = (params, timeout) => { return requestSocket(BagCmd.sendAllMyPkgGifts.encode, 1317, params, true, timeout, 'BagCmd.sendAllMyPkgGifts'); }
export const BagCmd_sendBarrage = (params, timeout) => { return requestSocket(BagCmd.sendBarrage.encode, 1019, params, true, timeout, 'BagCmd.sendBarrage'); }
export const BagCmd_sendGifts = (params, timeout) => { return requestSocket(BagCmd.sendGifts.encode, 1021, params, true, timeout, 'BagCmd.sendGifts'); }
export const BagCmd_sendImGift = (params, timeout) => { return requestSocket(BagCmd.sendImGift.encode, 1020, params, true, timeout, 'BagCmd.sendImGift'); }
export const BagCmd_sendPackageGift = (params, timeout) => { return requestSocket(BagCmd.sendPackageGift.encode, 1023, params, true, timeout, 'BagCmd.sendPackageGift'); }
export const BagCmd_sendPackageGifts = (params, timeout) => { return requestSocket(BagCmd.sendPackageGifts.encode, 1022, params, true, timeout, 'BagCmd.sendPackageGifts'); }
export const BagCmd_useCar = (params, timeout) => { return requestSocket(BagCmd.useCar.encode, 1016, params, true, timeout, 'BagCmd.useCar'); }
export const BagCmd_useDialogFrame = (params, timeout) => { return requestSocket(BagCmd.useDialogFrame.encode, 1018, params, true, timeout, 'BagCmd.useDialogFrame'); }
export const BagCmd_useHeardFrame = (params, timeout) => { return requestSocket(BagCmd.useHeardFrame.encode, 1017, params, true, timeout, 'BagCmd.useHeardFrame'); }
export const BagCmd_useMedal = (params, timeout) => { return requestSocket(BagCmd.useMedal.encode, 1234, params, true, timeout, 'BagCmd.useMedal'); }
export const CardCmd_getUserCard = (params, timeout) => { return requestSocket(CardCmd.getUserCard.encode, 1308, params, true, timeout, 'CardCmd.getUserCard'); }
export const CardCmd_getUserCardType = (params, timeout) => { return requestSocket(CardCmd.getUserCardType.encode, 1311, params, true, timeout, 'CardCmd.getUserCardType'); }
export const CardCmd_listRoomCard = (params, timeout) => { return requestSocket(CardCmd.listRoomCard.encode, 1310, params, true, timeout, 'CardCmd.listRoomCard'); }
export const CardCmd_listUserCard = (params, timeout) => { return requestSocket(CardCmd.listUserCard.encode, 1309, params, true, timeout, 'CardCmd.listUserCard'); }
export const CenterCmd_getEnterRoomList = (params, timeout) => { return requestSocket(CenterCmd.getEnterRoomList.encode, 1029, params, true, timeout, 'CenterCmd.getEnterRoomList'); }
export const CenterCmd_getFollowRoomList = (params, timeout) => { return requestSocket(CenterCmd.getFollowRoomList.encode, 1028, params, true, timeout, 'CenterCmd.getFollowRoomList'); }
export const CenterCmd_getFunRoomList = (params, timeout) => { return requestSocket(CenterCmd.getFunRoomList.encode, 1027, params, true, timeout, 'CenterCmd.getFunRoomList'); }
export const CenterCmd_getMusicList = (params, timeout) => { return requestSocket(CenterCmd.getMusicList.encode, 1031, params, true, timeout, 'CenterCmd.getMusicList'); }
export const CenterCmd_getMyVideoRoomList = (params, timeout) => { return requestSocket(CenterCmd.getMyVideoRoomList.encode, 1271, params, true, timeout, 'CenterCmd.getMyVideoRoomList'); }
export const CenterCmd_getRankInfo = (params, timeout) => { return requestSocket(CenterCmd.getRankInfo.encode, 1299, params, true, timeout, 'CenterCmd.getRankInfo'); }
export const CenterCmd_getRankList = (params, timeout) => { return requestSocket(CenterCmd.getRankList.encode, 1030, params, true, timeout, 'CenterCmd.getRankList'); }
export const CenterCmd_getRankRoomList = (params, timeout) => { return requestSocket(CenterCmd.getRankRoomList.encode, 1298, params, true, timeout, 'CenterCmd.getRankRoomList'); }
export const CenterCmd_getRecommendRoomId = (params, timeout) => { return requestSocket(CenterCmd.getRecommendRoomId.encode, 1224, params, true, timeout, 'CenterCmd.getRecommendRoomId'); }
export const CenterCmd_getRecommendVideoRoom = (params, timeout) => { return requestSocket(CenterCmd.getRecommendVideoRoom.encode, 1277, params, true, timeout, 'CenterCmd.getRecommendVideoRoom'); }
export const CenterCmd_getRoomRankList = (params, timeout) => { return requestSocket(CenterCmd.getRoomRankList.encode, 1178, params, true, timeout, 'CenterCmd.getRoomRankList'); }
export const CenterCmd_getSkillUserList = (params, timeout) => { return requestSocket(CenterCmd.getSkillUserList.encode, 1911, params, true, timeout, 'CenterCmd.getSkillUserList'); }
export const CenterCmd_randomRoomId = (params, timeout) => { return requestSocket(CenterCmd.randomRoomId.encode, 1186, params, true, timeout, 'CenterCmd.randomRoomId'); }
export const CenterCmd_searchFunRoom = (params, timeout) => { return requestSocket(CenterCmd.searchFunRoom.encode, 1026, params, true, timeout, 'CenterCmd.searchFunRoom'); }
export const CommentCmd_cancelLikeComment = (params, timeout) => { return requestSocket(CommentCmd.cancelLikeComment.encode, 1035, params, true, timeout, 'CommentCmd.cancelLikeComment'); }
export const CommentCmd_delComment = (params, timeout) => { return requestSocket(CommentCmd.delComment.encode, 1036, params, true, timeout, 'CommentCmd.delComment'); }
export const CommentCmd_issueComment = (params, timeout) => { return requestSocket(CommentCmd.issueComment.encode, 1032, params, true, timeout, 'CommentCmd.issueComment'); }
export const CommentCmd_likeComment = (params, timeout) => { return requestSocket(CommentCmd.likeComment.encode, 1034, params, true, timeout, 'CommentCmd.likeComment'); }
export const CommentCmd_listComment = (params, timeout) => { return requestSocket(CommentCmd.listComment.encode, 1033, params, true, timeout, 'CommentCmd.listComment'); }
export const DataCmd_actionData = (params, timeout) => { return requestSocket(DataCmd.actionData.encode, 1114, params, true, timeout, 'DataCmd.actionData'); }
export const DataCmd_changeLogo = (params, timeout) => { return requestSocket(DataCmd.changeLogo.encode, 1183, params, true, timeout, 'DataCmd.changeLogo'); }
export const DataCmd_clickTestSubject = (params, timeout) => { return requestSocket(DataCmd.clickTestSubject.encode, 1230, params, true, timeout, 'DataCmd.clickTestSubject'); }
export const DataCmd_delMoment = (params, timeout) => { return requestSocket(DataCmd.delMoment.encode, 1182, params, true, timeout, 'DataCmd.delMoment'); }
export const DataCmd_getCrossRoomMvp = (params, timeout) => { return requestSocket(DataCmd.getCrossRoomMvp.encode, 1322, params, true, timeout, 'DataCmd.getCrossRoomMvp'); }
export const DataCmd_getCrossRoomRank = (params, timeout) => { return requestSocket(DataCmd.getCrossRoomRank.encode, 1321, params, true, timeout, 'DataCmd.getCrossRoomRank'); }
export const DataCmd_getOnlineUserInfoList = (params, timeout) => { return requestSocket(DataCmd.getOnlineUserInfoList.encode, 1038, params, true, timeout, 'DataCmd.getOnlineUserInfoList'); }
export const DataCmd_getRandomMatch = (params, timeout) => { return requestSocket(DataCmd.getRandomMatch.encode, 1041, params, true, timeout, 'DataCmd.getRandomMatch'); }
export const DataCmd_getRecommendUserInfoList = (params, timeout) => { return requestSocket(DataCmd.getRecommendUserInfoList.encode, 1039, params, true, timeout, 'DataCmd.getRecommendUserInfoList'); }
export const DataCmd_getSameCharacters = (params, timeout) => { return requestSocket(DataCmd.getSameCharacters.encode, 1229, params, true, timeout, 'DataCmd.getSameCharacters'); }
export const DataCmd_getTestSubjectData = (params, timeout) => { return requestSocket(DataCmd.getTestSubjectData.encode, 1231, params, true, timeout, 'DataCmd.getTestSubjectData'); }
export const DataCmd_launchSelect = (params, timeout) => { return requestSocket(DataCmd.launchSelect.encode, 1037, params, true, timeout, 'DataCmd.launchSelect'); }
export const DataCmd_loveRingUserAction = (params, timeout) => { return requestSocket(DataCmd.loveRingUserAction.encode, 1236, params, true, timeout, 'DataCmd.loveRingUserAction'); }
export const DataCmd_prohibition = (params, timeout) => { return requestSocket(DataCmd.prohibition.encode, 1181, params, true, timeout, 'DataCmd.prohibition'); }
export const DataCmd_randomMatch = (params, timeout) => { return requestSocket(DataCmd.randomMatch.encode, 1040, params, true, timeout, 'DataCmd.randomMatch'); }
export const DataCmd_randomOnlineUserId = (params, timeout) => { return requestSocket(DataCmd.randomOnlineUserId.encode, 1172, params, true, timeout, 'DataCmd.randomOnlineUserId'); }
export const DataCmd_randomRoomId = (params, timeout) => { return requestSocket(DataCmd.randomRoomId.encode, 1173, params, true, timeout, 'DataCmd.randomRoomId'); }
export const DataCmd_sendSecretaryMessage = (params, timeout) => { return requestSocket(DataCmd.sendSecretaryMessage.encode, 1247, params, true, timeout, 'DataCmd.sendSecretaryMessage'); }
export const DataCmd_umengDevice = (params, timeout) => { return requestSocket(DataCmd.umengDevice.encode, 1240, params, true, timeout, 'DataCmd.umengDevice'); }
export const DataCmd_yellowReport = (params, timeout) => { return requestSocket(DataCmd.yellowReport.encode, 1188, params, true, timeout, 'DataCmd.yellowReport'); }
export const FishCmd_bet = (params, timeout) => { return requestSocket(FishCmd.bet.encode, 1290, params, true, timeout, 'FishCmd.bet'); }
export const FishCmd_drawCommission = (params, timeout) => { return requestSocket(FishCmd.drawCommission.encode, 1293, params, true, timeout, 'FishCmd.drawCommission'); }
export const FishCmd_enter = (params, timeout) => { return requestSocket(FishCmd.enter.encode, 1288, params, true, timeout, 'FishCmd.enter'); }
export const FishCmd_getBetLog = (params, timeout) => { return requestSocket(FishCmd.getBetLog.encode, 1296, params, true, timeout, 'FishCmd.getBetLog'); }
export const FishCmd_getCommission = (params, timeout) => { return requestSocket(FishCmd.getCommission.encode, 1292, params, true, timeout, 'FishCmd.getCommission'); }
export const FishCmd_getMyBets = (params, timeout) => { return requestSocket(FishCmd.getMyBets.encode, 1294, params, true, timeout, 'FishCmd.getMyBets'); }
export const FishCmd_getUserBetDetail = (params, timeout) => { return requestSocket(FishCmd.getUserBetDetail.encode, 1295, params, true, timeout, 'FishCmd.getUserBetDetail'); }
export const FishCmd_leave = (params, timeout) => { return requestSocket(FishCmd.leave.encode, 1289, params, true, timeout, 'FishCmd.leave'); }
export const FishCmd_sendGift = (params, timeout) => { return requestSocket(FishCmd.sendGift.encode, 1291, params, true, timeout, 'FishCmd.sendGift'); }
export const GiftPackageCmd_isBought = (params, timeout) => { return requestSocket(GiftPackageCmd.isBought.encode, 1042, params, true, timeout, 'GiftPackageCmd.isBought'); }
export const GiftPackageCmd_isPop = (params, timeout) => { return requestSocket(GiftPackageCmd.isPop.encode, 1043, params, true, timeout, 'GiftPackageCmd.isPop'); }
export const GiftPackageCmd_popSetting = (params, timeout) => { return requestSocket(GiftPackageCmd.popSetting.encode, 1044, params, true, timeout, 'GiftPackageCmd.popSetting'); }
export const GmCmd_dealGmcmd = (params, timeout) => { return requestSocket(GmCmd.dealGmcmd.encode, 1045, params, true, timeout, 'GmCmd.dealGmcmd'); }
export const GroupCmd_create = (params, timeout) => { return requestSocket(GroupCmd.create.encode, 1256, params, true, timeout, 'GroupCmd.create'); }
export const GroupCmd_delRedPoint = (params, timeout) => { return requestSocket(GroupCmd.delRedPoint.encode, 1266, params, true, timeout, 'GroupCmd.delRedPoint'); }
export const GroupCmd_enter = (params, timeout) => { return requestSocket(GroupCmd.enter.encode, 1259, params, true, timeout, 'GroupCmd.enter'); }
export const GroupCmd_enterBySelf = (params, timeout) => { return requestSocket(GroupCmd.enterBySelf.encode, 1281, params, true, timeout, 'GroupCmd.enterBySelf'); }
export const GroupCmd_getGroup = (params, timeout) => { return requestSocket(GroupCmd.getGroup.encode, 1264, params, true, timeout, 'GroupCmd.getGroup'); }
export const GroupCmd_getGroupInfos = (params, timeout) => { return requestSocket(GroupCmd.getGroupInfos.encode, 1283, params, true, timeout, 'GroupCmd.getGroupInfos'); }
export const GroupCmd_getMembers = (params, timeout) => { return requestSocket(GroupCmd.getMembers.encode, 1265, params, true, timeout, 'GroupCmd.getMembers'); }
export const GroupCmd_groupInfoList = (params, timeout) => { return requestSocket(GroupCmd.groupInfoList.encode, 1285, params, true, timeout, 'GroupCmd.groupInfoList'); }
export const GroupCmd_groupList = (params, timeout) => { return requestSocket(GroupCmd.groupList.encode, 1274, params, true, timeout, 'GroupCmd.groupList'); }
export const GroupCmd_hasGroupMemberLive = (params, timeout) => { return requestSocket(GroupCmd.hasGroupMemberLive.encode, 1284, params, true, timeout, 'GroupCmd.hasGroupMemberLive'); }
export const GroupCmd_inviteEnter = (params, timeout) => { return requestSocket(GroupCmd.inviteEnter.encode, 1257, params, true, timeout, 'GroupCmd.inviteEnter'); }
export const GroupCmd_kickOutMember = (params, timeout) => { return requestSocket(GroupCmd.kickOutMember.encode, 1260, params, true, timeout, 'GroupCmd.kickOutMember'); }
export const GroupCmd_leave = (params, timeout) => { return requestSocket(GroupCmd.leave.encode, 1258, params, true, timeout, 'GroupCmd.leave'); }
export const GroupCmd_modifyInfo = (params, timeout) => { return requestSocket(GroupCmd.modifyInfo.encode, 1261, params, true, timeout, 'GroupCmd.modifyInfo'); }
export const GroupCmd_ownGroupList = (params, timeout) => { return requestSocket(GroupCmd.ownGroupList.encode, 1278, params, true, timeout, 'GroupCmd.ownGroupList'); }
export const GroupCmd_report = (params, timeout) => { return requestSocket(GroupCmd.report.encode, 1287, params, true, timeout, 'GroupCmd.report'); }
export const GroupCmd_setNotFriendNeedAgree = (params, timeout) => { return requestSocket(GroupCmd.setNotFriendNeedAgree.encode, 1263, params, true, timeout, 'GroupCmd.setNotFriendNeedAgree'); }
export const GroupCmd_transfer = (params, timeout) => { return requestSocket(GroupCmd.transfer.encode, 1262, params, true, timeout, 'GroupCmd.transfer'); }
export const GuardianCmd_drawTask = (params, timeout) => { return requestSocket(GuardianCmd.drawTask.encode, 1213, params, true, timeout, 'GuardianCmd.drawTask'); }
export const GuardianCmd_drawTaskAward = (params, timeout) => { return requestSocket(GuardianCmd.drawTaskAward.encode, 1215, params, true, timeout, 'GuardianCmd.drawTaskAward'); }
export const GuardianCmd_getGuardians = (params, timeout) => { return requestSocket(GuardianCmd.getGuardians.encode, 1209, params, true, timeout, 'GuardianCmd.getGuardians'); }
export const GuardianCmd_inGuards = (params, timeout) => { return requestSocket(GuardianCmd.inGuards.encode, 1246, params, true, timeout, 'GuardianCmd.inGuards'); }
export const GuardianCmd_myGuardInfo = (params, timeout) => { return requestSocket(GuardianCmd.myGuardInfo.encode, 1211, params, true, timeout, 'GuardianCmd.myGuardInfo'); }
export const GuardianCmd_myGuardPartInfo = (params, timeout) => { return requestSocket(GuardianCmd.myGuardPartInfo.encode, 1223, params, true, timeout, 'GuardianCmd.myGuardPartInfo'); }
export const GuardianCmd_myGuardianInfo = (params, timeout) => { return requestSocket(GuardianCmd.myGuardianInfo.encode, 1210, params, true, timeout, 'GuardianCmd.myGuardianInfo'); }
export const GuardianCmd_setGuardianName = (params, timeout) => { return requestSocket(GuardianCmd.setGuardianName.encode, 1212, params, true, timeout, 'GuardianCmd.setGuardianName'); }
export const GuardianCmd_sign = (params, timeout) => { return requestSocket(GuardianCmd.sign.encode, 1214, params, true, timeout, 'GuardianCmd.sign'); }
export const HeartBeatCmd_heartBeat = (params, timeout) => { return requestSocket(HeartBeatCmd.heartBeat.encode, 1046, params, true, timeout, 'HeartBeatCmd.heartBeat'); }
export const LiveRoomCmd_applyExpense = (params, timeout) => { return requestSocket(LiveRoomCmd.applyExpense.encode, 1058, params, true, timeout, 'LiveRoomCmd.applyExpense'); }
export const LiveRoomCmd_applyFamily = (params, timeout) => { return requestSocket(LiveRoomCmd.applyFamily.encode, 1050, params, true, timeout, 'LiveRoomCmd.applyFamily'); }
export const LiveRoomCmd_applyLeaveFamily = (params, timeout) => { return requestSocket(LiveRoomCmd.applyLeaveFamily.encode, 1051, params, true, timeout, 'LiveRoomCmd.applyLeaveFamily'); }
export const LiveRoomCmd_applyMatchmaker = (params, timeout) => { return requestSocket(LiveRoomCmd.applyMatchmaker.encode, 1269, params, true, timeout, 'LiveRoomCmd.applyMatchmaker'); }
export const LiveRoomCmd_applyMatchmakerTask = (params, timeout) => { return requestSocket(LiveRoomCmd.applyMatchmakerTask.encode, 1279, params, true, timeout, 'LiveRoomCmd.applyMatchmakerTask'); }
export const LiveRoomCmd_auditAnchorApply = (params, timeout) => { return requestSocket(LiveRoomCmd.auditAnchorApply.encode, 1313, params, true, timeout, 'LiveRoomCmd.auditAnchorApply'); }
export const LiveRoomCmd_drawings = (params, timeout) => { return requestSocket(LiveRoomCmd.drawings.encode, 1055, params, true, timeout, 'LiveRoomCmd.drawings'); }
export const LiveRoomCmd_drawingsResult = (params, timeout) => { return requestSocket(LiveRoomCmd.drawingsResult.encode, 1056, params, true, timeout, 'LiveRoomCmd.drawingsResult'); }
export const LiveRoomCmd_drawingsStatus = (params, timeout) => { return requestSocket(LiveRoomCmd.drawingsStatus.encode, 1057, params, true, timeout, 'LiveRoomCmd.drawingsStatus'); }
export const LiveRoomCmd_familyExchange = (params, timeout) => { return requestSocket(LiveRoomCmd.familyExchange.encode, 1326, params, true, timeout, 'LiveRoomCmd.familyExchange'); }
export const LiveRoomCmd_familyExchangeGoldShell = (params, timeout) => { return requestSocket(LiveRoomCmd.familyExchangeGoldShell.encode, 1301, params, true, timeout, 'LiveRoomCmd.familyExchangeGoldShell'); }
export const LiveRoomCmd_forcedFamily = (params, timeout) => { return requestSocket(LiveRoomCmd.forcedFamily.encode, 1052, params, true, timeout, 'LiveRoomCmd.forcedFamily'); }
export const LiveRoomCmd_getCertificationData = (params, timeout) => { return requestSocket(LiveRoomCmd.getCertificationData.encode, 1054, params, true, timeout, 'LiveRoomCmd.getCertificationData'); }
export const LiveRoomCmd_getFamilyAnchorList = (params, timeout) => { return requestSocket(LiveRoomCmd.getFamilyAnchorList.encode, 1312, params, true, timeout, 'LiveRoomCmd.getFamilyAnchorList'); }
export const LiveRoomCmd_getFamilyList = (params, timeout) => { return requestSocket(LiveRoomCmd.getFamilyList.encode, 1047, params, true, timeout, 'LiveRoomCmd.getFamilyList'); }
export const LiveRoomCmd_getFamilyStatus = (params, timeout) => { return requestSocket(LiveRoomCmd.getFamilyStatus.encode, 1048, params, true, timeout, 'LiveRoomCmd.getFamilyStatus'); }
export const LiveRoomCmd_getLiveData = (params, timeout) => { return requestSocket(LiveRoomCmd.getLiveData.encode, 1195, params, true, timeout, 'LiveRoomCmd.getLiveData'); }
export const LiveRoomCmd_getLiveEarning = (params, timeout) => { return requestSocket(LiveRoomCmd.getLiveEarning.encode, 1061, params, true, timeout, 'LiveRoomCmd.getLiveEarning'); }
export const LiveRoomCmd_getLiveEarningData = (params, timeout) => { return requestSocket(LiveRoomCmd.getLiveEarningData.encode, 1306, params, true, timeout, 'LiveRoomCmd.getLiveEarningData'); }
export const LiveRoomCmd_getLiveEarningList = (params, timeout) => { return requestSocket(LiveRoomCmd.getLiveEarningList.encode, 1062, params, true, timeout, 'LiveRoomCmd.getLiveEarningList'); }
export const LiveRoomCmd_getLiveExchangeList = (params, timeout) => { return requestSocket(LiveRoomCmd.getLiveExchangeList.encode, 1065, params, true, timeout, 'LiveRoomCmd.getLiveExchangeList'); }
export const LiveRoomCmd_getLiveExchangeMoney = (params, timeout) => { return requestSocket(LiveRoomCmd.getLiveExchangeMoney.encode, 1064, params, true, timeout, 'LiveRoomCmd.getLiveExchangeMoney'); }
export const LiveRoomCmd_getLiveExpense = (params, timeout) => { return requestSocket(LiveRoomCmd.getLiveExpense.encode, 1059, params, true, timeout, 'LiveRoomCmd.getLiveExpense'); }
export const LiveRoomCmd_getLiveExpenseList = (params, timeout) => { return requestSocket(LiveRoomCmd.getLiveExpenseList.encode, 1060, params, true, timeout, 'LiveRoomCmd.getLiveExpenseList'); }
export const LiveRoomCmd_getLiveRecv = (params, timeout) => { return requestSocket(LiveRoomCmd.getLiveRecv.encode, 1193, params, true, timeout, 'LiveRoomCmd.getLiveRecv'); }
export const LiveRoomCmd_getLiveRecvList = (params, timeout) => { return requestSocket(LiveRoomCmd.getLiveRecvList.encode, 1194, params, true, timeout, 'LiveRoomCmd.getLiveRecvList'); }
export const LiveRoomCmd_getMatchmakerEarningData = (params, timeout) => { return requestSocket(LiveRoomCmd.getMatchmakerEarningData.encode, 1307, params, true, timeout, 'LiveRoomCmd.getMatchmakerEarningData'); }
export const LiveRoomCmd_getMyFamily = (params, timeout) => { return requestSocket(LiveRoomCmd.getMyFamily.encode, 1049, params, true, timeout, 'LiveRoomCmd.getMyFamily'); }
export const LiveRoomCmd_liveExchange = (params, timeout) => { return requestSocket(LiveRoomCmd.liveExchange.encode, 1325, params, true, timeout, 'LiveRoomCmd.liveExchange'); }
export const LiveRoomCmd_liveExchangeGoldShell = (params, timeout) => { return requestSocket(LiveRoomCmd.liveExchangeGoldShell.encode, 1063, params, true, timeout, 'LiveRoomCmd.liveExchangeGoldShell'); }
export const LiveRoomCmd_myLiveInfo = (params, timeout) => { return requestSocket(LiveRoomCmd.myLiveInfo.encode, 1270, params, true, timeout, 'LiveRoomCmd.myLiveInfo'); }
export const LiveRoomCmd_needCreateFamily = (params, timeout) => { return requestSocket(LiveRoomCmd.needCreateFamily.encode, 1053, params, true, timeout, 'LiveRoomCmd.needCreateFamily'); }
export const LiveRoomCmd_queryCertification = (params, timeout) => { return requestSocket(LiveRoomCmd.queryCertification.encode, 1198, params, true, timeout, 'LiveRoomCmd.queryCertification'); }
export const MomentCmd_MomentMedia = (params, timeout) => { return requestSocket(MomentCmd.MomentMedia.encode, 1935, params, true, timeout, 'MomentCmd.MomentMedia'); }
export const MomentCmd_addFocusTopic = (params, timeout) => { return requestSocket(MomentCmd.addFocusTopic.encode, 1941, params, true, timeout, 'MomentCmd.addFocusTopic'); }
export const MomentCmd_cancelFocusTopic = (params, timeout) => { return requestSocket(MomentCmd.cancelFocusTopic.encode, 1942, params, true, timeout, 'MomentCmd.cancelFocusTopic'); }
export const MomentCmd_cancelLikeMoment = (params, timeout) => { return requestSocket(MomentCmd.cancelLikeMoment.encode, 1080, params, true, timeout, 'MomentCmd.cancelLikeMoment'); }
export const MomentCmd_createTopic = (params, timeout) => { return requestSocket(MomentCmd.createTopic.encode, 1936, params, true, timeout, 'MomentCmd.createTopic'); }
export const MomentCmd_delMoment = (params, timeout) => { return requestSocket(MomentCmd.delMoment.encode, 1084, params, true, timeout, 'MomentCmd.delMoment'); }
export const MomentCmd_getTopicData = (params, timeout) => { return requestSocket(MomentCmd.getTopicData.encode, 1167, params, true, timeout, 'MomentCmd.getTopicData'); }
export const MomentCmd_getTopicDatas = (params, timeout) => { return requestSocket(MomentCmd.getTopicDatas.encode, 1166, params, true, timeout, 'MomentCmd.getTopicDatas'); }
export const MomentCmd_getTopicMoments = (params, timeout) => { return requestSocket(MomentCmd.getTopicMoments.encode, 1168, params, true, timeout, 'MomentCmd.getTopicMoments'); }
export const MomentCmd_issueMoment = (params, timeout) => { return requestSocket(MomentCmd.issueMoment.encode, 1078, params, true, timeout, 'MomentCmd.issueMoment'); }
export const MomentCmd_likeMoment = (params, timeout) => { return requestSocket(MomentCmd.likeMoment.encode, 1079, params, true, timeout, 'MomentCmd.likeMoment'); }
export const MomentCmd_listLikeMoments = (params, timeout) => { return requestSocket(MomentCmd.listLikeMoments.encode, 1939, params, true, timeout, 'MomentCmd.listLikeMoments'); }
export const MomentCmd_listMomentMedia = (params, timeout) => { return requestSocket(MomentCmd.listMomentMedia.encode, 1086, params, true, timeout, 'MomentCmd.listMomentMedia'); }
export const MomentCmd_listMoments = (params, timeout) => { return requestSocket(MomentCmd.listMoments.encode, 1083, params, true, timeout, 'MomentCmd.listMoments'); }
export const MomentCmd_momentSquare = (params, timeout) => { return requestSocket(MomentCmd.momentSquare.encode, 1077, params, true, timeout, 'MomentCmd.momentSquare'); }
export const MomentCmd_nextVoiceCard = (params, timeout) => { return requestSocket(MomentCmd.nextVoiceCard.encode, 1199, params, true, timeout, 'MomentCmd.nextVoiceCard'); }
export const MomentCmd_reportMoment = (params, timeout) => { return requestSocket(MomentCmd.reportMoment.encode, 1085, params, true, timeout, 'MomentCmd.reportMoment'); }
export const MomentCmd_searchTopic = (params, timeout) => { return requestSocket(MomentCmd.searchTopic.encode, 1938, params, true, timeout, 'MomentCmd.searchTopic'); }
export const MomentCmd_setReadMoment = (params, timeout) => { return requestSocket(MomentCmd.setReadMoment.encode, 1940, params, true, timeout, 'MomentCmd.setReadMoment'); }
export const MomentCmd_shareMoment = (params, timeout) => { return requestSocket(MomentCmd.shareMoment.encode, 1237, params, true, timeout, 'MomentCmd.shareMoment'); }
export const MomentCmd_shieldingMoment = (params, timeout) => { return requestSocket(MomentCmd.shieldingMoment.encode, 1081, params, true, timeout, 'MomentCmd.shieldingMoment'); }
export const MomentCmd_topicSquare = (params, timeout) => { return requestSocket(MomentCmd.topicSquare.encode, 1937, params, true, timeout, 'MomentCmd.topicSquare'); }
export const MomentCmd_viewMoment = (params, timeout) => { return requestSocket(MomentCmd.viewMoment.encode, 1082, params, true, timeout, 'MomentCmd.viewMoment'); }
export const MyCmd_addLover = (params, timeout) => { return requestSocket(MyCmd.addLover.encode, 1091, params, true, timeout, 'MyCmd.addLover'); }
export const MyCmd_addStrangerMsg = (params, timeout) => { return requestSocket(MyCmd.addStrangerMsg.encode, 1115, params, true, timeout, 'MyCmd.addStrangerMsg'); }
export const MyCmd_addSysGMemberSuccess = (params, timeout) => { return requestSocket(MyCmd.addSysGMemberSuccess.encode, 1096, params, true, timeout, 'MyCmd.addSysGMemberSuccess'); }
export const MyCmd_bindMobile = (params, timeout) => { return requestSocket(MyCmd.bindMobile.encode, 1101, params, true, timeout, 'MyCmd.bindMobile'); }
export const MyCmd_blackInfoList = (params, timeout) => { return requestSocket(MyCmd.blackInfoList.encode, 1196, params, true, timeout, 'MyCmd.blackInfoList'); }
export const MyCmd_blackList = (params, timeout) => { return requestSocket(MyCmd.blackList.encode, 1191, params, true, timeout, 'MyCmd.blackList'); }
export const MyCmd_breakStranger = (params, timeout) => { return requestSocket(MyCmd.breakStranger.encode, 1286, params, true, timeout, 'MyCmd.breakStranger'); }
export const MyCmd_changeMobile = (params, timeout) => { return requestSocket(MyCmd.changeMobile.encode, 1117, params, true, timeout, 'MyCmd.changeMobile'); }
export const MyCmd_characterTest = (params, timeout) => { return requestSocket(MyCmd.characterTest.encode, 1232, params, true, timeout, 'MyCmd.characterTest'); }
export const MyCmd_checkNickNameExist = (params, timeout) => { return requestSocket(MyCmd.checkNickNameExist.encode, 1945, params, true, timeout, 'MyCmd.checkNickNameExist'); }
export const MyCmd_delAllVideoDateLog = (params, timeout) => { return requestSocket(MyCmd.delAllVideoDateLog.encode, 1276, params, true, timeout, 'MyCmd.delAllVideoDateLog'); }
export const MyCmd_delLookMeRecord = (params, timeout) => { return requestSocket(MyCmd.delLookMeRecord.encode, 1095, params, true, timeout, 'MyCmd.delLookMeRecord'); }
export const MyCmd_delRedPoint = (params, timeout) => { return requestSocket(MyCmd.delRedPoint.encode, 1233, params, true, timeout, 'MyCmd.delRedPoint'); }
export const MyCmd_enterOfficialGroup = (params, timeout) => { return requestSocket(MyCmd.enterOfficialGroup.encode, 1318, params, true, timeout, 'MyCmd.enterOfficialGroup'); }
export const MyCmd_favourHall = (params, timeout) => { return requestSocket(MyCmd.favourHall.encode, 1315, params, true, timeout, 'MyCmd.favourHall'); }
export const MyCmd_followEnterRoom = (params, timeout) => { return requestSocket(MyCmd.followEnterRoom.encode, 1098, params, true, timeout, 'MyCmd.followEnterRoom'); }
export const MyCmd_getDeviceConfig = (params, timeout) => { return requestSocket(MyCmd.getDeviceConfig.encode, 1107, params, true, timeout, 'MyCmd.getDeviceConfig'); }
export const MyCmd_getFavourRoomList = (params, timeout) => { return requestSocket(MyCmd.getFavourRoomList.encode, 1316, params, true, timeout, 'MyCmd.getFavourRoomList'); }
export const MyCmd_getFriendList = (params, timeout) => { return requestSocket(MyCmd.getFriendList.encode, 1092, params, true, timeout, 'MyCmd.getFriendList'); }
export const MyCmd_getLookMeList = (params, timeout) => { return requestSocket(MyCmd.getLookMeList.encode, 1093, params, true, timeout, 'MyCmd.getLookMeList'); }
export const MyCmd_getNewLookMeNum = (params, timeout) => { return requestSocket(MyCmd.getNewLookMeNum.encode, 1094, params, true, timeout, 'MyCmd.getNewLookMeNum'); }
export const MyCmd_getPersonPage = (params, timeout) => { return requestSocket(MyCmd.getPersonPage.encode, 1089, params, true, timeout, 'MyCmd.getPersonPage'); }
export const MyCmd_getStrangerInfo = (params, timeout) => { return requestSocket(MyCmd.getStrangerInfo.encode, 1248, params, true, timeout, 'MyCmd.getStrangerInfo'); }
export const MyCmd_getUserDetail = (params, timeout) => { return requestSocket(MyCmd.getUserDetail.encode, 1302, params, true, timeout, 'MyCmd.getUserDetail'); }
export const MyCmd_getUserInfoList = (params, timeout) => { return requestSocket(MyCmd.getUserInfoList.encode, 1088, params, true, timeout, 'MyCmd.getUserInfoList'); }
export const MyCmd_getUserLevel = (params, timeout) => { return requestSocket(MyCmd.getUserLevel.encode, 1105, params, true, timeout, 'MyCmd.getUserLevel'); }
export const MyCmd_getUserList = (params, timeout) => { return requestSocket(MyCmd.getUserList.encode, 1087, params, true, timeout, 'MyCmd.getUserList'); }
export const MyCmd_getVideoDateLogList = (params, timeout) => { return requestSocket(MyCmd.getVideoDateLogList.encode, 1275, params, true, timeout, 'MyCmd.getVideoDateLogList'); }
export const MyCmd_invisible = (params, timeout) => { return requestSocket(MyCmd.invisible.encode, 1119, params, true, timeout, 'MyCmd.invisible'); }
export const MyCmd_kickOnlineUser = (params, timeout) => { return requestSocket(MyCmd.kickOnlineUser.encode, 1304, params, true, timeout, 'MyCmd.kickOnlineUser'); }
export const MyCmd_markCharacterTest = (params, timeout) => { return requestSocket(MyCmd.markCharacterTest.encode, 1235, params, true, timeout, 'MyCmd.markCharacterTest'); }
export const MyCmd_modifyCoordinate = (params, timeout) => { return requestSocket(MyCmd.modifyCoordinate.encode, 1238, params, true, timeout, 'MyCmd.modifyCoordinate'); }
export const MyCmd_modifyUserDetail = (params, timeout) => { return requestSocket(MyCmd.modifyUserDetail.encode, 1303, params, true, timeout, 'MyCmd.modifyUserDetail'); }
export const MyCmd_modifyUserInfo = (params, timeout) => { return requestSocket(MyCmd.modifyUserInfo.encode, 1090, params, true, timeout, 'MyCmd.modifyUserInfo'); }
export const MyCmd_openTips = (params, timeout) => { return requestSocket(MyCmd.openTips.encode, 1100, params, true, timeout, 'MyCmd.openTips'); }
export const MyCmd_optYoungPwd = (params, timeout) => { return requestSocket(MyCmd.optYoungPwd.encode, 1200, params, true, timeout, 'MyCmd.optYoungPwd'); }
export const MyCmd_playMusic = (params, timeout) => { return requestSocket(MyCmd.playMusic.encode, 1120, params, true, timeout, 'MyCmd.playMusic'); }
export const MyCmd_postLocation = (params, timeout) => { return requestSocket(MyCmd.postLocation.encode, 1104, params, true, timeout, 'MyCmd.postLocation'); }
export const MyCmd_pullBlack = (params, timeout) => { return requestSocket(MyCmd.pullBlack.encode, 1190, params, true, timeout, 'MyCmd.pullBlack'); }
export const MyCmd_pullBlackStatus = (params, timeout) => { return requestSocket(MyCmd.pullBlackStatus.encode, 1192, params, true, timeout, 'MyCmd.pullBlackStatus'); }
export const MyCmd_redoImHeadUrl = (params, timeout) => { return requestSocket(MyCmd.redoImHeadUrl.encode, 1097, params, true, timeout, 'MyCmd.redoImHeadUrl'); }
export const MyCmd_replyOfficialUser = (params, timeout) => { return requestSocket(MyCmd.replyOfficialUser.encode, 1118, params, true, timeout, 'MyCmd.replyOfficialUser'); }
export const MyCmd_reportUser = (params, timeout) => { return requestSocket(MyCmd.reportUser.encode, 1116, params, true, timeout, 'MyCmd.reportUser'); }
export const MyCmd_setDeviceConfig = (params, timeout) => { return requestSocket(MyCmd.setDeviceConfig.encode, 1108, params, true, timeout, 'MyCmd.setDeviceConfig'); }
export const MyCmd_setFriendRemark = (params, timeout) => { return requestSocket(MyCmd.setFriendRemark.encode, 1103, params, true, timeout, 'MyCmd.setFriendRemark'); }
export const MyCmd_setInvitationCode = (params, timeout) => { return requestSocket(MyCmd.setInvitationCode.encode, 1102, params, true, timeout, 'MyCmd.setInvitationCode'); }
export const MyCmd_setPassword = (params, timeout) => { return requestSocket(MyCmd.setPassword.encode, 1106, params, true, timeout, 'MyCmd.setPassword'); }
export const MyCmd_shakeMicUp = (params, timeout) => { return requestSocket(MyCmd.shakeMicUp.encode, 1099, params, true, timeout, 'MyCmd.shakeMicUp'); }
export const MyCmd_shieldingHandle = (params, timeout) => { return requestSocket(MyCmd.shieldingHandle.encode, 1111, params, true, timeout, 'MyCmd.shieldingHandle'); }
export const MyCmd_unbindMobile = (params, timeout) => { return requestSocket(MyCmd.unbindMobile.encode, 1109, params, true, timeout, 'MyCmd.unbindMobile'); }
export const MyCmd_updatePassword = (params, timeout) => { return requestSocket(MyCmd.updatePassword.encode, 1305, params, true, timeout, 'MyCmd.updatePassword'); }
export const NewLiveRoomCmd_applyExpense = (params, timeout) => { return requestSocket(NewLiveRoomCmd.applyExpense.encode, 1900, params, true, timeout, 'NewLiveRoomCmd.applyExpense'); }
export const NewLiveRoomCmd_checkIsSetPayPassword = (params, timeout) => { return requestSocket(NewLiveRoomCmd.checkIsSetPayPassword.encode, 1908, params, true, timeout, 'NewLiveRoomCmd.checkIsSetPayPassword'); }
export const NewLiveRoomCmd_exchangeGoldShell = (params, timeout) => { return requestSocket(NewLiveRoomCmd.exchangeGoldShell.encode, 1901, params, true, timeout, 'NewLiveRoomCmd.exchangeGoldShell'); }
export const NewLiveRoomCmd_joinPayExpense = (params, timeout) => { return requestSocket(NewLiveRoomCmd.joinPayExpense.encode, 1909, params, true, timeout, 'NewLiveRoomCmd.joinPayExpense'); }
export const NewLiveRoomCmd_setPayPassword = (params, timeout) => { return requestSocket(NewLiveRoomCmd.setPayPassword.encode, 1902, params, true, timeout, 'NewLiveRoomCmd.setPayPassword'); }
export const NotificationCmd_cleanNotification = (params, timeout) => { return requestSocket(NotificationCmd.cleanNotification.encode, 1124, params, true, timeout, 'NotificationCmd.cleanNotification'); }
export const NotificationCmd_delNotification = (params, timeout) => { return requestSocket(NotificationCmd.delNotification.encode, 1123, params, true, timeout, 'NotificationCmd.delNotification'); }
export const NotificationCmd_getUnreadCount = (params, timeout) => { return requestSocket(NotificationCmd.getUnreadCount.encode, 1943, params, true, timeout, 'NotificationCmd.getUnreadCount'); }
export const NotificationCmd_listNotification = (params, timeout) => { return requestSocket(NotificationCmd.listNotification.encode, 1121, params, true, timeout, 'NotificationCmd.listNotification'); }
export const NotificationCmd_triggerNote = (params, timeout) => { return requestSocket(NotificationCmd.triggerNote.encode, 1125, params, true, timeout, 'NotificationCmd.triggerNote'); }
export const NotificationCmd_viewNotification = (params, timeout) => { return requestSocket(NotificationCmd.viewNotification.encode, 1122, params, true, timeout, 'NotificationCmd.viewNotification'); }
export const PublicChatCmd_getLatestMessageList = (params, timeout) => { return requestSocket(PublicChatCmd.getLatestMessageList.encode, 1913, params, true, timeout, 'PublicChatCmd.getLatestMessageList'); }
export const PublicChatCmd_sendPublicMessage = (params, timeout) => { return requestSocket(PublicChatCmd.sendPublicMessage.encode, 1912, params, true, timeout, 'PublicChatCmd.sendPublicMessage'); }
export const RechargeCmd_confirmOrderPayTimeOut = (params, timeout) => { return requestSocket(RechargeCmd.confirmOrderPayTimeOut.encode, 1904, params, true, timeout, 'RechargeCmd.confirmOrderPayTimeOut'); }
export const RechargeCmd_getReceivedGoldShellData = (params, timeout) => { return requestSocket(RechargeCmd.getReceivedGoldShellData.encode, 1910, params, true, timeout, 'RechargeCmd.getReceivedGoldShellData'); }
export const RechargeCmd_getRechargeCount = (params, timeout) => { return requestSocket(RechargeCmd.getRechargeCount.encode, 1127, params, true, timeout, 'RechargeCmd.getRechargeCount'); }
export const RechargeCmd_getRechargeData = (params, timeout) => { return requestSocket(RechargeCmd.getRechargeData.encode, 1126, params, true, timeout, 'RechargeCmd.getRechargeData'); }
export const RechargeCmd_getRechargeTotal = (params, timeout) => { return requestSocket(RechargeCmd.getRechargeTotal.encode, 1272, params, true, timeout, 'RechargeCmd.getRechargeTotal'); }
export const RechargeCmd_getSendGoldShellLog = (params, timeout) => { return requestSocket(RechargeCmd.getSendGoldShellLog.encode, 1906, params, true, timeout, 'RechargeCmd.getSendGoldShellLog'); }
export const RechargeCmd_sendGoldShell = (params, timeout) => { return requestSocket(RechargeCmd.sendGoldShell.encode, 1905, params, true, timeout, 'RechargeCmd.sendGoldShell'); }
export const RedEnvelopeCmd_addInvitationCode = (params, timeout) => { return requestSocket(RedEnvelopeCmd.addInvitationCode.encode, 1206, params, true, timeout, 'RedEnvelopeCmd.addInvitationCode'); }
export const RedEnvelopeCmd_applyExpense = (params, timeout) => { return requestSocket(RedEnvelopeCmd.applyExpense.encode, 1228, params, true, timeout, 'RedEnvelopeCmd.applyExpense'); }
export const RedEnvelopeCmd_canGetLoginRedEnvelope = (params, timeout) => { return requestSocket(RedEnvelopeCmd.canGetLoginRedEnvelope.encode, 1202, params, true, timeout, 'RedEnvelopeCmd.canGetLoginRedEnvelope'); }
export const RedEnvelopeCmd_checkAccountStatus = (params, timeout) => { return requestSocket(RedEnvelopeCmd.checkAccountStatus.encode, 1255, params, true, timeout, 'RedEnvelopeCmd.checkAccountStatus'); }
export const RedEnvelopeCmd_drawings = (params, timeout) => { return requestSocket(RedEnvelopeCmd.drawings.encode, 1208, params, true, timeout, 'RedEnvelopeCmd.drawings'); }
export const RedEnvelopeCmd_drawingsResult = (params, timeout) => { return requestSocket(RedEnvelopeCmd.drawingsResult.encode, 1216, params, true, timeout, 'RedEnvelopeCmd.drawingsResult'); }
export const RedEnvelopeCmd_drawingsStatus = (params, timeout) => { return requestSocket(RedEnvelopeCmd.drawingsStatus.encode, 1217, params, true, timeout, 'RedEnvelopeCmd.drawingsStatus'); }
export const RedEnvelopeCmd_exchangeGoldShell = (params, timeout) => { return requestSocket(RedEnvelopeCmd.exchangeGoldShell.encode, 1207, params, true, timeout, 'RedEnvelopeCmd.exchangeGoldShell'); }
export const RedEnvelopeCmd_getBalance = (params, timeout) => { return requestSocket(RedEnvelopeCmd.getBalance.encode, 1220, params, true, timeout, 'RedEnvelopeCmd.getBalance'); }
export const RedEnvelopeCmd_getExchangeList = (params, timeout) => { return requestSocket(RedEnvelopeCmd.getExchangeList.encode, 1219, params, true, timeout, 'RedEnvelopeCmd.getExchangeList'); }
export const RedEnvelopeCmd_getExchangeMoney = (params, timeout) => { return requestSocket(RedEnvelopeCmd.getExchangeMoney.encode, 1218, params, true, timeout, 'RedEnvelopeCmd.getExchangeMoney'); }
export const RedEnvelopeCmd_getExpenseList = (params, timeout) => { return requestSocket(RedEnvelopeCmd.getExpenseList.encode, 1227, params, true, timeout, 'RedEnvelopeCmd.getExpenseList'); }
export const RedEnvelopeCmd_getExpenseMoney = (params, timeout) => { return requestSocket(RedEnvelopeCmd.getExpenseMoney.encode, 1226, params, true, timeout, 'RedEnvelopeCmd.getExpenseMoney'); }
export const RedEnvelopeCmd_getLiveRedEnvelope = (params, timeout) => { return requestSocket(RedEnvelopeCmd.getLiveRedEnvelope.encode, 1205, params, true, timeout, 'RedEnvelopeCmd.getLiveRedEnvelope'); }
export const RedEnvelopeCmd_getLiveRemainTime = (params, timeout) => { return requestSocket(RedEnvelopeCmd.getLiveRemainTime.encode, 1204, params, true, timeout, 'RedEnvelopeCmd.getLiveRemainTime'); }
export const RedEnvelopeCmd_getLoginRedEnvelope = (params, timeout) => { return requestSocket(RedEnvelopeCmd.getLoginRedEnvelope.encode, 1203, params, true, timeout, 'RedEnvelopeCmd.getLoginRedEnvelope'); }
export const RedEnvelopeCmd_getRedEnvelopeAmount = (params, timeout) => { return requestSocket(RedEnvelopeCmd.getRedEnvelopeAmount.encode, 1221, params, true, timeout, 'RedEnvelopeCmd.getRedEnvelopeAmount'); }
export const RedEnvelopeCmd_getSetting = (params, timeout) => { return requestSocket(RedEnvelopeCmd.getSetting.encode, 1222, params, true, timeout, 'RedEnvelopeCmd.getSetting'); }
export const RedEnvelopeCmd_inviteRedEnvelopeList = (params, timeout) => { return requestSocket(RedEnvelopeCmd.inviteRedEnvelopeList.encode, 1254, params, true, timeout, 'RedEnvelopeCmd.inviteRedEnvelopeList'); }
export const RedEnvelopeCmd_listRedEnvelope = (params, timeout) => { return requestSocket(RedEnvelopeCmd.listRedEnvelope.encode, 1201, params, true, timeout, 'RedEnvelopeCmd.listRedEnvelope'); }
export const RedEnvelopeCmd_logShareInvitationCode = (params, timeout) => { return requestSocket(RedEnvelopeCmd.logShareInvitationCode.encode, 1225, params, true, timeout, 'RedEnvelopeCmd.logShareInvitationCode'); }
export const RoomCmd_action = (params, timeout) => { return requestSocket(RoomCmd.action.encode, 1130, params, true, timeout, 'RoomCmd.action'); }
export const RoomCmd_anchorCheck = (params, timeout) => { return requestSocket(RoomCmd.anchorCheck.encode, 1280, params, true, timeout, 'RoomCmd.anchorCheck'); }
export const RoomCmd_atRoomUser = (params, timeout) => { return requestSocket(RoomCmd.atRoomUser.encode, 1146, params, true, timeout, 'RoomCmd.atRoomUser'); }
export const RoomCmd_breakInvite = (params, timeout) => { return requestSocket(RoomCmd.breakInvite.encode, 1170, params, true, timeout, 'RoomCmd.breakInvite'); }
export const RoomCmd_checkCanEnter = (params, timeout) => { return requestSocket(RoomCmd.checkCanEnter.encode, 1132, params, true, timeout, 'RoomCmd.checkCanEnter'); }
export const RoomCmd_checkPwd = (params, timeout) => { return requestSocket(RoomCmd.checkPwd.encode, 1131, params, true, timeout, 'RoomCmd.checkPwd'); }
export const RoomCmd_dragonBall = (params, timeout) => { return requestSocket(RoomCmd.dragonBall.encode, 1245, params, true, timeout, 'RoomCmd.dragonBall'); }
export const RoomCmd_enter = (params, timeout) => { return requestSocket(RoomCmd.enter.encode, 1133, params, true, timeout, 'RoomCmd.enter'); }
export const RoomCmd_getCrossRoomBase = (params, timeout) => { return requestSocket(RoomCmd.getCrossRoomBase.encode, 1323, params, true, timeout, 'RoomCmd.getCrossRoomBase'); }
export const RoomCmd_getCrossRoomPkLog = (params, timeout) => { return requestSocket(RoomCmd.getCrossRoomPkLog.encode, 1324, params, true, timeout, 'RoomCmd.getCrossRoomPkLog'); }
export const RoomCmd_getDarkRoomMemberList = (params, timeout) => { return requestSocket(RoomCmd.getDarkRoomMemberList.encode, 1903, params, true, timeout, 'RoomCmd.getDarkRoomMemberList'); }
export const RoomCmd_getEnterRoomList = (params, timeout) => { return requestSocket(RoomCmd.getEnterRoomList.encode, 1151, params, true, timeout, 'RoomCmd.getEnterRoomList'); }
export const RoomCmd_getForbidTime = (params, timeout) => { return requestSocket(RoomCmd.getForbidTime.encode, 1177, params, true, timeout, 'RoomCmd.getForbidTime'); }
export const RoomCmd_getFunRoomDividedRateInfos = (params, timeout) => { return requestSocket(RoomCmd.getFunRoomDividedRateInfos.encode, 1141, params, true, timeout, 'RoomCmd.getFunRoomDividedRateInfos'); }
export const RoomCmd_getJobId = (params, timeout) => { return requestSocket(RoomCmd.getJobId.encode, 1187, params, true, timeout, 'RoomCmd.getJobId'); }
export const RoomCmd_getLatelyBg = (params, timeout) => { return requestSocket(RoomCmd.getLatelyBg.encode, 1136, params, true, timeout, 'RoomCmd.getLatelyBg'); }
export const RoomCmd_getLivePushInfo = (params, timeout) => { return requestSocket(RoomCmd.getLivePushInfo.encode, 1149, params, true, timeout, 'RoomCmd.getLivePushInfo'); }
export const RoomCmd_getOnlineMembers = (params, timeout) => { return requestSocket(RoomCmd.getOnlineMembers.encode, 1140, params, true, timeout, 'RoomCmd.getOnlineMembers'); }
export const RoomCmd_getOnlineRoomId = (params, timeout) => { return requestSocket(RoomCmd.getOnlineRoomId.encode, 1145, params, true, timeout, 'RoomCmd.getOnlineRoomId'); }
export const RoomCmd_getOnlines = (params, timeout) => { return requestSocket(RoomCmd.getOnlines.encode, 1144, params, true, timeout, 'RoomCmd.getOnlines'); }
export const RoomCmd_getRecreations = (params, timeout) => { return requestSocket(RoomCmd.getRecreations.encode, 1150, params, true, timeout, 'RoomCmd.getRecreations'); }
export const RoomCmd_getRoomConfigData = (params, timeout) => { return requestSocket(RoomCmd.getRoomConfigData.encode, 1137, params, true, timeout, 'RoomCmd.getRoomConfigData'); }
export const RoomCmd_getRoomData = (params, timeout) => { return requestSocket(RoomCmd.getRoomData.encode, 1138, params, true, timeout, 'RoomCmd.getRoomData'); }
export const RoomCmd_getRoomInfo = (params, timeout) => { return requestSocket(RoomCmd.getRoomInfo.encode, 1180, params, true, timeout, 'RoomCmd.getRoomInfo'); }
export const RoomCmd_getRoomInfoList = (params, timeout) => { return requestSocket(RoomCmd.getRoomInfoList.encode, 1300, params, true, timeout, 'RoomCmd.getRoomInfoList'); }
export const RoomCmd_getRoomMicData = (params, timeout) => { return requestSocket(RoomCmd.getRoomMicData.encode, 1139, params, true, timeout, 'RoomCmd.getRoomMicData'); }
export const RoomCmd_getRoomMicQues = (params, timeout) => { return requestSocket(RoomCmd.getRoomMicQues.encode, 1282, params, true, timeout, 'RoomCmd.getRoomMicQues'); }
export const RoomCmd_getRoomName = (params, timeout) => { return requestSocket(RoomCmd.getRoomName.encode, 1143, params, true, timeout, 'RoomCmd.getRoomName'); }
export const RoomCmd_getRoomState = (params, timeout) => { return requestSocket(RoomCmd.getRoomState.encode, 1142, params, true, timeout, 'RoomCmd.getRoomState'); }
export const RoomCmd_getRoomStatus = (params, timeout) => { return requestSocket(RoomCmd.getRoomStatus.encode, 1328, params, true, timeout, 'RoomCmd.getRoomStatus'); }
export const RoomCmd_getRoomUserInfo = (params, timeout) => { return requestSocket(RoomCmd.getRoomUserInfo.encode, 1330, params, true, timeout, 'RoomCmd.getRoomUserInfo'); }
export const RoomCmd_getSquareOnlines = (params, timeout) => { return requestSocket(RoomCmd.getSquareOnlines.encode, 1268, params, true, timeout, 'RoomCmd.getSquareOnlines'); }
export const RoomCmd_getStartRoomInfo = (params, timeout) => { return requestSocket(RoomCmd.getStartRoomInfo.encode, 1239, params, true, timeout, 'RoomCmd.getStartRoomInfo'); }
export const RoomCmd_getUserHallIds = (params, timeout) => { return requestSocket(RoomCmd.getUserHallIds.encode, 1314, params, true, timeout, 'RoomCmd.getUserHallIds'); }
export const RoomCmd_getUserHeartRank = (params, timeout) => { return requestSocket(RoomCmd.getUserHeartRank.encode, 1273, params, true, timeout, 'RoomCmd.getUserHeartRank'); }
export const RoomCmd_inviteAllEnter = (params, timeout) => { return requestSocket(RoomCmd.inviteAllEnter.encode, 1297, params, true, timeout, 'RoomCmd.inviteAllEnter'); }
export const RoomCmd_inviteEnterRoom = (params, timeout) => { return requestSocket(RoomCmd.inviteEnterRoom.encode, 1169, params, true, timeout, 'RoomCmd.inviteEnterRoom'); }
export const RoomCmd_isInMic = (params, timeout) => { return requestSocket(RoomCmd.isInMic.encode, 1148, params, true, timeout, 'RoomCmd.isInMic'); }
export const RoomCmd_leave = (params, timeout) => { return requestSocket(RoomCmd.leave.encode, 1134, params, true, timeout, 'RoomCmd.leave'); }
export const RoomCmd_managers = (params, timeout) => { return requestSocket(RoomCmd.managers.encode, 1185, params, true, timeout, 'RoomCmd.managers'); }
export const RoomCmd_modifyRoom = (params, timeout) => { return requestSocket(RoomCmd.modifyRoom.encode, 1135, params, true, timeout, 'RoomCmd.modifyRoom'); }
export const RoomCmd_reportRoom = (params, timeout) => { return requestSocket(RoomCmd.reportRoom.encode, 1147, params, true, timeout, 'RoomCmd.reportRoom'); }
export const RoomCmd_responseInvite = (params, timeout) => { return requestSocket(RoomCmd.responseInvite.encode, 1171, params, true, timeout, 'RoomCmd.responseInvite'); }
export const RoomCmd_setIsAcptMicInvt = (params, timeout) => { return requestSocket(RoomCmd.setIsAcptMicInvt.encode, 1267, params, true, timeout, 'RoomCmd.setIsAcptMicInvt'); }
export const RoomCmd_setManager = (params, timeout) => { return requestSocket(RoomCmd.setManager.encode, 1184, params, true, timeout, 'RoomCmd.setManager'); }
export const RoomCmd_start = (params, timeout) => { return requestSocket(RoomCmd.start.encode, 1128, params, true, timeout, 'RoomCmd.start'); }
export const RoomCmd_stop = (params, timeout) => { return requestSocket(RoomCmd.stop.encode, 1129, params, true, timeout, 'RoomCmd.stop'); }
export const ServiceCmd_checkMatchSms = (params, timeout) => { return requestCenter(ServiceCmd.checkMatchSms.encode, 1154, params, timeout); }
export const ServiceCmd_clientLog = (params, timeout) => { return requestCenter(ServiceCmd.clientLog.encode, 1153, params, timeout); }
export const ServiceCmd_sendGetMsgCode = (params, timeout) => { return requestCenter(ServiceCmd.sendGetMsgCode.encode, 1152, params, timeout); }
export const ShortcutMessageCmd_addShortcutMessage = (params, timeout) => { return requestSocket(ShortcutMessageCmd.addShortcutMessage.encode, 1930, params, true, timeout, 'ShortcutMessageCmd.addShortcutMessage'); }
export const ShortcutMessageCmd_deleteShortcutMessage = (params, timeout) => { return requestSocket(ShortcutMessageCmd.deleteShortcutMessage.encode, 1932, params, true, timeout, 'ShortcutMessageCmd.deleteShortcutMessage'); }
export const ShortcutMessageCmd_getShortcutMessageList = (params, timeout) => { return requestSocket(ShortcutMessageCmd.getShortcutMessageList.encode, 1931, params, true, timeout, 'ShortcutMessageCmd.getShortcutMessageList'); }
export const ShortcutMessageCmd_modifyShortcutMessage = (params, timeout) => { return requestSocket(ShortcutMessageCmd.modifyShortcutMessage.encode, 1933, params, true, timeout, 'ShortcutMessageCmd.modifyShortcutMessage'); }
export const ShortcutMessageCmd_sortShortcutMessage = (params, timeout) => { return requestSocket(ShortcutMessageCmd.sortShortcutMessage.encode, 1934, params, true, timeout, 'ShortcutMessageCmd.sortShortcutMessage'); }
export const SkillChatCmd_callAnchor = (params, timeout) => { return requestSocket(SkillChatCmd.callAnchor.encode, 1914, params, true, timeout, 'SkillChatCmd.callAnchor'); }
export const SkillChatCmd_cancelCall = (params, timeout) => { return requestSocket(SkillChatCmd.cancelCall.encode, 1915, params, true, timeout, 'SkillChatCmd.cancelCall'); }
export const SkillChatCmd_chkChatRoom = (params, timeout) => { return requestSocket(SkillChatCmd.chkChatRoom.encode, 1944, params, true, timeout, 'SkillChatCmd.chkChatRoom'); }
export const SkillChatCmd_evalChat = (params, timeout) => { return requestSocket(SkillChatCmd.evalChat.encode, 1926, params, true, timeout, 'SkillChatCmd.evalChat'); }
export const SkillChatCmd_getChatEarningList = (params, timeout) => { return requestSocket(SkillChatCmd.getChatEarningList.encode, 1925, params, true, timeout, 'SkillChatCmd.getChatEarningList'); }
export const SkillChatCmd_getLiveChatList = (params, timeout) => { return requestSocket(SkillChatCmd.getLiveChatList.encode, 1924, params, true, timeout, 'SkillChatCmd.getLiveChatList'); }
export const SkillChatCmd_pickUpCall = (params, timeout) => { return requestSocket(SkillChatCmd.pickUpCall.encode, 1916, params, true, timeout, 'SkillChatCmd.pickUpCall'); }
export const SkillCmd_applyUserSkill = (params, timeout) => { return requestSocket(SkillCmd.applyUserSkill.encode, 1917, params, true, timeout, 'SkillCmd.applyUserSkill'); }
export const SkillCmd_getSkillInfo = (params, timeout) => { return requestSocket(SkillCmd.getSkillInfo.encode, 1922, params, true, timeout, 'SkillCmd.getSkillInfo'); }
export const SkillCmd_getUserSkillInfo = (params, timeout) => { return requestSocket(SkillCmd.getUserSkillInfo.encode, 1920, params, true, timeout, 'SkillCmd.getUserSkillInfo'); }
export const SkillCmd_getUserSkillList = (params, timeout) => { return requestSocket(SkillCmd.getUserSkillList.encode, 1919, params, true, timeout, 'SkillCmd.getUserSkillList'); }
export const SkillCmd_judgeShouldSendDataCard = (params, timeout) => { return requestSocket(SkillCmd.judgeShouldSendDataCard.encode, 1928, params, true, timeout, 'SkillCmd.judgeShouldSendDataCard'); }
export const SkillCmd_listSkill = (params, timeout) => { return requestSocket(SkillCmd.listSkill.encode, 1921, params, true, timeout, 'SkillCmd.listSkill'); }
export const SkillCmd_modifyUserSkillLabels = (params, timeout) => { return requestSocket(SkillCmd.modifyUserSkillLabels.encode, 1918, params, true, timeout, 'SkillCmd.modifyUserSkillLabels'); }
export const SkillCmd_querySkillApplyState = (params, timeout) => { return requestSocket(SkillCmd.querySkillApplyState.encode, 1923, params, true, timeout, 'SkillCmd.querySkillApplyState'); }
export const SkillCmd_recordSendDataCard = (params, timeout) => { return requestSocket(SkillCmd.recordSendDataCard.encode, 1929, params, true, timeout, 'SkillCmd.recordSendDataCard'); }
export const SkillCmd_switchNoDisturbMode = (params, timeout) => { return requestSocket(SkillCmd.switchNoDisturbMode.encode, 1927, params, true, timeout, 'SkillCmd.switchNoDisturbMode'); }
export const SmashEggCmd_can = (params, timeout) => { return requestSocket(SmashEggCmd.can.encode, 1249, params, true, timeout, 'SmashEggCmd.can'); }
export const SmashEggCmd_getHorseLamp = (params, timeout) => { return requestSocket(SmashEggCmd.getHorseLamp.encode, 1253, params, true, timeout, 'SmashEggCmd.getHorseLamp'); }
export const SmashEggCmd_getLog = (params, timeout) => { return requestSocket(SmashEggCmd.getLog.encode, 1251, params, true, timeout, 'SmashEggCmd.getLog'); }
export const SmashEggCmd_getSmashList = (params, timeout) => { return requestSocket(SmashEggCmd.getSmashList.encode, 1319, params, true, timeout, 'SmashEggCmd.getSmashList'); }
export const SmashEggCmd_listGift = (params, timeout) => { return requestSocket(SmashEggCmd.listGift.encode, 1252, params, true, timeout, 'SmashEggCmd.listGift'); }
export const SmashEggCmd_smash = (params, timeout) => { return requestSocket(SmashEggCmd.smash.encode, 1250, params, true, timeout, 'SmashEggCmd.smash'); }
export const TestCmd_testCmd = (params, timeout) => { return requestSocket(TestCmd.testCmd.encode, 1155, params, true, timeout, 'TestCmd.testCmd'); }
export const UserCertificationCmd_getUserCertification = (params, timeout) => { return requestSocket(UserCertificationCmd.getUserCertification.encode, 1157, params, true, timeout, 'UserCertificationCmd.getUserCertification'); }
export const UserCertificationCmd_postUserCertification = (params, timeout) => { return requestSocket(UserCertificationCmd.postUserCertification.encode, 1156, params, true, timeout, 'UserCertificationCmd.postUserCertification'); }
export const UserCertificationCmd_saveUserCertification = (params, timeout) => { return requestSocket(UserCertificationCmd.saveUserCertification.encode, 1320, params, true, timeout, 'UserCertificationCmd.saveUserCertification'); }
export const UserCmd_getChannelInfo = (params, timeout) => { return requestSocket(UserCmd.getChannelInfo.encode, 1176, params, false, timeout, 'UserCmd.getChannelInfo'); }
export const UserCmd_heartBeat = (params, timeout) => { return requestSocket(UserCmd.heartBeat.encode, 1164, params, false, timeout, 'UserCmd.heartBeat'); }
export const UserCmd_login = (params, timeout) => { return requestSocket(UserCmd.login.encode, 1158, params, false, timeout, 'UserCmd.login'); }
export const UserCmd_logon = (params, timeout) => { return requestSocket(UserCmd.logon.encode, 1160, params, false, timeout, 'UserCmd.logon'); }
export const UserCmd_logonTcp = (params, timeout) => { return requestSocket(UserCmd.logonTcp.encode, 1165, params, false, timeout, 'UserCmd.logonTcp'); }
export const UserCmd_offline = (params, timeout) => { return requestSocket(UserCmd.offline.encode, 1161, params, false, timeout, 'UserCmd.offline'); }
export const UserCmd_register = (params, timeout) => { return requestSocket(UserCmd.register.encode, 1159, params, false, timeout, 'UserCmd.register'); }
export const UserCmd_retrievePwd = (params, timeout) => { return requestSocket(UserCmd.retrievePwd.encode, 1162, params, false, timeout, 'UserCmd.retrievePwd'); }
export const UserCmd_sysoffline = (params, timeout) => { return requestSocket(UserCmd.sysoffline.encode, 1175, params, false, timeout, 'UserCmd.sysoffline'); }
export const UserCmd_verifySmsCode = (params, timeout) => { return requestSocket(UserCmd.verifySmsCode.encode, 1163, params, false, timeout, 'UserCmd.verifySmsCode'); }




SocketModel.setup(UserCmd_login, UserCmd_logon, UserCmd_heartBeat, UserCmd.login.encode, UserCmd.logon.encode);

export const checkLogonByLaunch = SocketModel.checkLogonByLaunch;
export const checkLogon = SocketModel.checkLogon;
export const requestLogin = SocketModel.requestLogin;
export const tryRequestLoginByCache = () => { return requestSocket(null, 0, null, true, 0, 'localTryLogin') };
export const logout = SocketModel.logout;
